# Generated by Django 5.2.8 on 2025-11-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_sistema',
            field=models.CharField(default='#0d6efd', help_text='Cor principal do sistema (Hex)', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mensagem_cupom',
            field=models.CharField(blank=True, default='Obrigado pela preferência!', max_length=200),
        ),
    ]
