# Generated by Django 5.2.8 on 2025-11-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_cor_sistema_empresa_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ambiente_fiscal',
            field=models.CharField(choices=[('HOMOLOGACAO', 'Teste'), ('PRODUCAO', 'Valendo')], default='HOMOLOGACAO', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token_api_fiscal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
