# Generated by Django 5.2.8 on 2025-11-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_ambiente_fiscal_empresa_csc_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plano',
            field=models.CharField(choices=[('ESSENCIAL', 'Essencial (R$ 129)'), ('PRO', 'Profissional (R$ 249)'), ('EXPANSAO', 'Expansão (Corporativo)')], default='ESSENCIAL', max_length=20),
        ),
    ]
