# Generated by Django 5.2.8 on 2025-11-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
