# Generated by Django 5.2.8 on 2025-11-30 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_asaas_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField()),
                ('motivo', models.CharField(choices=[('DEFEITO', 'Defeito / Avaria'), ('PERDA', 'Perda / Roubo'), ('VALIDADE', 'Vencimento'), ('USO_INTERNO', 'Uso Interno / Consumo'), ('ENTRADA', 'Entrada Avulsa / Correção')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_ajuste', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DUVIDA', 'Dúvida'), ('PROBLEMA', 'Problema / Erro'), ('SUGESTAO', 'Sugestão de Melhoria'), ('FINANCEIRO', 'Assunto Financeiro')], max_length=20)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='suporte/')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Análise'), ('RESOLVIDO', 'Resolvido')], default='ABERTO', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('resposta_admin', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
