# Generated by Django 5.2.8 on 2025-12-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ajusteestoque_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ramo_atividade',
            field=models.CharField(choices=[('ROUPAS', 'Loja de Roupas / Calçados'), ('MERCADO', 'Mercado / Conveniência'), ('SERVICOS', 'Prestação de Serviços'), ('OUTROS', 'Outros / Genérico')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
