# Generated by Django 5.2.8 on 2025-12-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa_ramo_atividade_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, help_text='Ex: Azul, Vermelho, Estampado', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, help_text='Ex: P, M, G, 38, 42', max_length=10, null=True),
        ),
    ]
